// Types + client loader for the data snapshot generated by build_data_json.py.
// Mirrors the shape of web/public/data/snapshot.json.

export type AtBatResult =
  | "single"
  | "double"
  | "triple"
  | "home_run"
  | "sacrifice_fly"
  | "fielders_choice"
  | "error"
  | "batter_out"
  | "batter_out_advance_runners"
  | "infield_fly"
  | "other_out"
  | "dropped_third_strike_batter_out"
  | "strike_out";

export type FieldZone = "infield" | "outfield" | "other";
export type FieldSide = "left" | "middle" | "right" | "other";

export interface RunnersBefore {
  "1": string | null;
  "2": string | null;
  "3": string | null;
}

export interface AtBat {
  person_key: string;
  batter: string | null;
  season_year: number;
  date: string | null;
  opponent: string | null;
  result: AtBatResult | string | null;
  play_type: string | null;
  defender_position: string | null;
  field_zone: FieldZone;
  field_side: FieldSide;
  runs_scored: number;
  run_scoring: boolean;
  x: number | null;
  y: number | null;
  transaction_seq: number;
  event_id: string | null;
  runners_before: RunnersBefore;
}

export interface PlayerSeason {
  season_year: number;
  PA: number;
  wOBA: number | null;
  BMBL_plus: number | null;
  qualified: boolean;
}

export interface PlayerGame {
  date: string;
  season_year: number;
  opponent: string | null;
  PA: number;
  AB: number;
  H: number;
  HR: number;
  wOBA_game: number | null;
}

export interface Player {
  display_name: string;
  seasons: PlayerSeason[];
  games: PlayerGame[];
}

export interface CareerWeighted {
  person_key: string;
  display_name: string;
  seasons_qualified: number;
  career_PA: number;
  career_BMBLplus_weighted: number;
  seasons_played: string;
  peak_season_year: number;
  peak_BMBLplus: number;
}

export interface MvpLine {
  person_key: string;
  display_name: string;
  score: number;
  PA: number;
  AB: number;
  H: number;
  "1B": number;
  "2B": number;
  "3B": number;
  HR: number;
  TB: number;
  XBH: number;
  SF: number;
  ROE: number;
  outs: number;
  runs_scored: number;
}

export interface MvpNight {
  date: string;
  season_year: number;
  opponents: string[];
  mvp: MvpLine;
  runner_up: MvpLine | null;
  top: MvpLine[];
  justification: string;
}

export interface Snapshot {
  generated_at: string;
  players: Record<string, Player>;
  career_weighted: Record<string, CareerWeighted>;
  weights: Record<string, number>;
  at_bats: AtBat[];
  mvp_nights: MvpNight[];
}
