// Types + client loader for the data snapshot generated by build_data_json.py.
// Mirrors the shape of web/public/data/snapshot.json.

export type AtBatResult =
  | "single"
  | "double"
  | "triple"
  | "home_run"
  | "sacrifice_fly"
  | "fielders_choice"
  | "error"
  | "batter_out"
  | "batter_out_advance_runners"
  | "infield_fly"
  | "other_out"
  | "dropped_third_strike_batter_out"
  | "strike_out";

export type FieldZone = "infield" | "outfield" | "other";
export type FieldSide = "left" | "middle" | "right" | "other";

export interface BaseSnapshot {
  "1": string | null;
  "2": string | null;
  "3": string | null;
}
// Kept as an alias so older imports still work.
export type RunnersBefore = BaseSnapshot;

/**
 * One runner's transition during a single at-bat.
 *   from = 0 means the batter (just stepped in); 1/2/3 = previously on that base.
 *   to   = 1/2/3 means new base; 4 = scored / crossed home; "out" = put out.
 */
export interface RunnerMove {
  name: string;
  from: 0 | 1 | 2 | 3;
  to: 1 | 2 | 3 | 4 | "out";
}

export interface AtBat {
  person_key: string;
  batter: string | null;
  season_year: number;
  date: string | null;
  opponent: string | null;
  result: AtBatResult | string | null;
  play_type: string | null;
  defender_position: string | null;
  field_zone: FieldZone;
  field_side: FieldSide;
  runs_scored: number;
  run_scoring: boolean;
  x: number | null;
  y: number | null;
  transaction_seq: number;
  event_id: string | null;
  runners_before: BaseSnapshot;
  // Phase 3.5 additions — present on every at-bat in newly built snapshots.
  runners_after: BaseSnapshot;
  runner_moves: RunnerMove[];
  half_inning_id: string | null;
}

export interface PlayerSeason {
  season_year: number;
  PA: number;
  wOBA: number | null;
  BMBL_plus: number | null;
  qualified: boolean;
}

export interface PlayerGame {
  date: string;
  season_year: number;
  opponent: string | null;
  PA: number;
  AB: number;
  H: number;
  HR: number;
  wOBA_game: number | null;
}

export interface Player {
  display_name: string;
  seasons: PlayerSeason[];
  games: PlayerGame[];
}

export interface CareerWeighted {
  person_key: string;
  display_name: string;
  seasons_qualified: number;
  career_PA: number;
  career_BMBLplus_weighted: number;
  seasons_played: string;
  peak_season_year: number;
  peak_BMBLplus: number;
}

export interface MvpLine {
  person_key: string;
  display_name: string;
  score: number;
  PA: number;
  AB: number;
  H: number;
  "1B": number;
  "2B": number;
  "3B": number;
  HR: number;
  TB: number;
  XBH: number;
  SF: number;
  ROE: number;
  outs: number;
  runs_scored: number;
}

export interface MvpNight {
  date: string;
  season_year: number;
  opponents: string[];
  mvp: MvpLine;
  runner_up: MvpLine | null;
  top: MvpLine[];
  justification: string;
}

export interface Snapshot {
  generated_at: string;
  players: Record<string, Player>;
  career_weighted: Record<string, CareerWeighted>;
  weights: Record<string, number>;
  at_bats: AtBat[];
  mvp_nights: MvpNight[];
}

// ─── Active-roster filtering ─────────────────────────────────────────────
// The snapshot contains every player who ever appeared (32 currently); the
// planning UIs only care about people who actually still play. A player is
// "active" if they showed up in the most recent season AND have enough
// career PA to count as a regular (not a one-off guest).
//
// The default threshold (25 PA) excludes casual one-game appearances but
// keeps season-long subs. Pass `{ minPA: 0 }` to include everyone who
// played this season; pass `{ allSeasons: true }` to include retirees.

const DEFAULT_MIN_CAREER_PA = 25;

export interface RosterPlayer {
  key: string;
  display_name: string;
}

export interface RosterOptions {
  /** Override career-PA threshold. */
  minPA?: number;
  /** Include players who didn't play in the most recent season (defaults false). */
  allSeasons?: boolean;
}

/** Most recent season_year that appears anywhere in the snapshot. */
export function latestSeason(snap: Snapshot): number {
  let max = 0;
  for (const p of Object.values(snap.players)) {
    for (const s of p.seasons || []) {
      if (s.season_year > max) max = s.season_year;
    }
  }
  return max;
}

function careerPA(p: Player): number {
  return (p.seasons || []).reduce((sum, s) => sum + (s.PA || 0), 0);
}

function playedIn(p: Player, year: number): boolean {
  return (p.seasons || []).some((s) => s.season_year === year && s.PA > 0);
}

/** Returns the active roster — sorted alphabetically by display name. */
export function getActiveRoster(
  snap: Snapshot,
  opts: RosterOptions = {},
): RosterPlayer[] {
  const minPA = opts.minPA ?? DEFAULT_MIN_CAREER_PA;
  const current = latestSeason(snap);
  const out: RosterPlayer[] = [];
  for (const [key, p] of Object.entries(snap.players)) {
    if (!opts.allSeasons && !playedIn(p, current)) continue;
    if (careerPA(p) < minPA) continue;
    out.push({ key, display_name: p.display_name || key });
  }
  out.sort((a, b) => a.display_name.localeCompare(b.display_name));
  return out;
}

/** Convenience: the full roster, including retirees and one-off appearances. */
export function getFullRoster(snap: Snapshot): RosterPlayer[] {
  return Object.entries(snap.players)
    .map(([key, p]) => ({ key, display_name: p.display_name || key }))
    .sort((a, b) => a.display_name.localeCompare(b.display_name));
}
